# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            AI Journal
tagline:          'Artificial Intelligence | Machine learning | Deep learning | NLP | Reinforcement learning'
description:      Making AI accessible | Democraticizing AI
url:              http://aijournal.github.io
baseurl:          /

author:
  name:           'AI Journal'
  url:            https://twitter.com/aijournalyt

paginate:         5

# Custom vars
version:          2.1.0

google_analytics: UA-101180150-1

github:
  repo:           https://github.com/aijournal

gems: [jekyll-paginate,jekyll-gist]
