# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            AI Journal
tagline:          'Artificial Intelligence | Machine learning | Deep learning | NLP | Reinforcement learning'
description:      'Subscribe to our Youtube channel'
url:              http://aijournal.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/aijournalyt

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/aijournal
